import { toWide } from "../../../../utils/toWide";
import { ICONS } from "../icons";
import { PAGE_MODES, PAGE_TYPES } from "../pages/pageTypes";

import type { IconData } from "../icons";
import type { PageMode, PageType } from "../pages/pageTypes";

export const ICON_MAP_BY_MODE = {
	[PAGE_MODES.BROKEN]: ICONS.BROKEN,
	[PAGE_MODES.CAR_STATE]: ICONS.CAR_INFO_1,
	[PAGE_MODES.CONDUCTOR]: ICONS.CONDUCTOR,
	[PAGE_MODES.CORRECTION]: ICONS.CORRECTION,
	[PAGE_MODES.DRIVER]: ICONS.DRIVER,
	[PAGE_MODES.EMBEDDED_MANUAL]: ICONS.EMBEDDED_MANUAL,
	[PAGE_MODES.MAINTENANCE]: ICONS.MAINTENANCE,
	[PAGE_MODES.MENU]: ICONS.MENU,
	[PAGE_MODES.OCCUPANCY_RATE]: ICONS.OCCUPANCY_RATE,
	[PAGE_MODES.OTHER_SERIES]: ICONS.OTHER_SERIES,
	[PAGE_MODES.TABLE_OF_CONTENTS]: ICONS.TABLE_OF_CONTENTS_1,
	[PAGE_MODES.WORK_SETTING]: ICONS.WORK_SETTING_1,
} as const satisfies Record<PageMode, IconData>;

export const PAGE_NAME_MAP = {
	// Menu pages
	[PAGE_TYPES.MENU]: "メニュー",
	[PAGE_TYPES.OCCUPANCY_RATE]: "乗車率",
	[PAGE_TYPES.CAR_DETECTION]: "車両検知",
	[PAGE_TYPES.SET_LOCATION]: "地点登録",
	[PAGE_TYPES.TABLE_OF_CONTENTS]: "目　次",

	// Other Series pages
	[PAGE_TYPES.OTHER_SERIES_DRIVER_INFO]: "他形式車併結",
	[PAGE_TYPES.OTHER_SERIES_SUB_SETTING]: "他形式車併結",
	[PAGE_TYPES.OTHER_SERIES_ANNOUNCE]: "他形式車併結",
	[PAGE_TYPES.OTHER_SERIES_REDUCE_SPEED]: "他形式車併結",

	// Maintenance pages
	[PAGE_TYPES.MAINTENANCE_MENU]: "検　修",
	[PAGE_TYPES.MAINTENANCE_CTRL_TEST]: "機器試験",
	[PAGE_TYPES.MAINTENANCE_COMM_STATE]: "伝送情報",
	[PAGE_TYPES.MAINTENANCE_SPEC_RECORD]: "性能記録",
	[PAGE_TYPES.MAINTENANCE_BROKEN_LIST]: "記録内容",
	[PAGE_TYPES.MAINTENANCE_TEST_RUN]: "検修試運転",
	[PAGE_TYPES.MAINTENANCE_DI_DO]: toWide("DI/DO"),
	[PAGE_TYPES.MAINTENANCE_AIR_COND_STATE]: "空調状態",
	[PAGE_TYPES.MAINTENANCE_DISPLAY_TEST]: "機器試験",

	// Setting pages
	[PAGE_TYPES.SETTING_ENTRANCE]: "設　定",
	[PAGE_TYPES.SETTING_MENU]: "設　定",
	[PAGE_TYPES.SETTING_MONITOR]: "設　定",

	// Correction pages
	[PAGE_TYPES.CORRECTION_MENU]: "補　正",
	[PAGE_TYPES.CORRECTION_TIME]: "時刻設定",
	[PAGE_TYPES.LOCATION_CORRECTION]: "地点補正",
	// Car State pages
	[PAGE_TYPES.SWITCHES]: "車両状態",
	[PAGE_TYPES.POWER]: "車両状態",
	[PAGE_TYPES.BRAKE]: "車両状態",
	[PAGE_TYPES.THREE_PHASE_AC]: "車両状態",
	[PAGE_TYPES.POWER_BRAKE]: "車両状態",

	// Conductor pages
	[PAGE_TYPES.CONDUCTOR_INFO]: "車　掌",
	[PAGE_TYPES.CONDUCTOR_SERVICE]: "車　掌",
	[PAGE_TYPES.CONDUCTOR_AIR_COND_MODE]: "車　掌",
	[PAGE_TYPES.CONDUCTOR_AIR_COND_VENT]: "車　掌",
	[PAGE_TYPES.CONDUCTOR_AIR_COND_SUB]: "車　掌",
	[PAGE_TYPES.CONDUCTOR_AIR_COND_FAN]: "車　掌",
	[PAGE_TYPES.CONDUCTOR_315]: "車　掌",
	// Work Setting pages
	[PAGE_TYPES.WORK_SETTING_TOP]: "運行設定",
	[PAGE_TYPES.WORK_SETTING_TYPE]: "運行設定",
	[PAGE_TYPES.WORK_SETTING_SEAT]: "運行設定",

	// Driver pages
	[PAGE_TYPES.DRIVER_INFO]: "運転士",
	[PAGE_TYPES.REDUCE_SPEED]: "運転士",
	[PAGE_TYPES.ROOM_LIGHT]: "運転士",
	[PAGE_TYPES.BROKEN]: "運転士",
} as const satisfies Record<PageType, string>;
