import type { PropsWithChildren } from "react";
import { memo } from "react";

import CanvasObjectGroup from "../../../../canvas-renderer/objects/CanvasObjectGroup";
import { DISPLAY_HEIGHT, DISPLAY_WIDTH, HEADER_HEIGHT } from "../constants";
import HeaderArea from "../header/HeaderArea";
import { ICONS } from "../icons";
import { PAGE_TYPES } from "../pages/pageTypes";

import { useCurrentPageType } from "./CurrentPageContext";

import type { IconData } from "../icons";
import type { PageType } from "../pages/pageTypes";

export default memo<PropsWithChildren>(function WithoutFooterPageFrame({
	children,
}) {
	const pageType = useCurrentPageType();
	return (
		<>
			<HeaderArea
				icon={ICON_MAP_BY_PAGE[pageType]}
				pageName="メニュー"
				trainNumber="1234"
				trainType="普通"
				trainDestination="大垣"
				timeMinutes={5}
			/>
			<CanvasObjectGroup
				relX={0}
				relY={HEADER_HEIGHT}
				width={DISPLAY_WIDTH}
				height={DISPLAY_HEIGHT - HEADER_HEIGHT}>
				{children}
			</CanvasObjectGroup>
		</>
	);
});

const ICON_MAP_BY_PAGE = {
	// Menu pages
	[PAGE_TYPES.MENU]: ICONS.MENU,
	[PAGE_TYPES.OCCUPANCY_RATE]: ICONS.OCCUPANCY_RATE,
	[PAGE_TYPES.CAR_DETECTION]: ICONS.MENU,
	[PAGE_TYPES.SET_LOCATION]: ICONS.CORRECTION,
	[PAGE_TYPES.TABLE_OF_CONTENTS]: ICONS.TABLE_OF_CONTENTS_1,

	// Other Series pages
	[PAGE_TYPES.OTHER_SERIES_DRIVER_INFO]: ICONS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_SUB_SETTING]: ICONS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_ANNOUNCE_1]: ICONS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_ANNOUNCE_2]: ICONS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_BROKEN]: ICONS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_WORK_SETTING]: ICONS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_WORK_SETTING_MENU]: ICONS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_REDUCE_SPEED]: ICONS.OTHER_SERIES,

	// Maintenance pages
	[PAGE_TYPES["MAINTENANCE-MENU"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["MAINTENANCE-CTRL_TEST"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["MAINTENANCE-COMM_STATE"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["MAINTENANCE-SPEC_RECORD"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["MAINTENANCE-BROKEN_LIST"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["MAINTENANCE-TEST_RUN"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["MAINTENANCE-DI_DO"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["MAINTENANCE-AIR_COND_STATE"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["MAINTENANCE-DISPLAY_TEST"]]: ICONS.MAINTENANCE,

	// Setting pages
	[PAGE_TYPES["SETTING-ENTRANCE"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["SETTING-MENU"]]: ICONS.MAINTENANCE,
	[PAGE_TYPES["SETTING-MONITOR"]]: ICONS.MAINTENANCE,

	// Correction pages
	[PAGE_TYPES["CORRECTION-MENU"]]: ICONS.CORRECTION,
	[PAGE_TYPES["CORRECTION-TIME"]]: ICONS.CORRECTION,

	// Car State pages
	[PAGE_TYPES["CAR_STATE-SWITCHES"]]: ICONS.CAR_INFO_1,
	[PAGE_TYPES["CAR_STATE-POWER"]]: ICONS.CAR_INFO_1,
	[PAGE_TYPES["CAR_STATE-BRAKE"]]: ICONS.CAR_INFO_1,
	[PAGE_TYPES["CAR_STATE-THREE_PHASE_AC"]]: ICONS.CAR_INFO_1,
	[PAGE_TYPES["CAR_STATE-POWER_BRAKE"]]: ICONS.CAR_INFO_1,

	// Conductor pages
	[PAGE_TYPES["CONDUCTOR-INFO"]]: ICONS.CONDUCTOR,
	[PAGE_TYPES["CONDUCTOR-SERVICE"]]: ICONS.CONDUCTOR,
	[PAGE_TYPES["CONDUCTOR-AIR_COND"]]: ICONS.CONDUCTOR,
	[PAGE_TYPES["CONDUCTOR-LOCATION_CORRECTION"]]: ICONS.CONDUCTOR,
	[PAGE_TYPES["CONDUCTOR-CAR_STATE"]]: ICONS.CONDUCTOR,
	[PAGE_TYPES["CONDUCTOR-315"]]: ICONS.CONDUCTOR,

	// Work Setting pages
	[PAGE_TYPES["WORK_SETTING-TOP"]]: ICONS.WORK_SETTING_1,
	[PAGE_TYPES["WORK_SETTING-TYPE"]]: ICONS.WORK_SETTING_1,
	[PAGE_TYPES["WORK_SETTING-SEAT"]]: ICONS.WORK_SETTING_1,

	// Driver pages
	[PAGE_TYPES["DRIVER-INFO"]]: ICONS.DRIVER,
	[PAGE_TYPES["DRIVER-REDUCE_SPEED"]]: ICONS.DRIVER,
	[PAGE_TYPES["DRIVER-ROOM_LIGHT"]]: ICONS.DRIVER,
	[PAGE_TYPES["DRIVER-LOCATION_CORRECTION"]]: ICONS.DRIVER,
} as const satisfies Record<PageType, IconData>;
