const createPages = <const T extends readonly string[]>(arr: T) =>
	Object.fromEntries(arr.map((item) => [item, item])) as {
		[K in T[number]]: K;
	};

export const PAGE_TYPES = createPages([
	"MENU",
	"OCCUPANCY_RATE",
	"CAR_DETECTION",
	"SET_LOCATION",
	"TABLE_OF_CONTENTS",

	"OTHER_SERIES",
	"OTHER_SERIES_SUB_SETTING",
	"OTHER_SERIES_ANNOUNCE_1",
	"OTHER_SERIES_ANNOUNCE_2",
	"OTHER_SERIES_BROKEN",
	"OTHER_SERIES_WORK_SETTING",
	"OTHER_SERIES_WORK_SETTING_MENU",
	"OTHER_SERIES_REDUCE_SPEED",

	"EMBEDDED_MANUAL_1",

	"MAINTENANCE-MENU",
	"MAINTENANCE-CTRL_TEST",
	"MAINTENANCE-COMM_STATE",
	"MAINTENANCE-SPEC_RECORD",
	"MAINTENANCE-BROKEN_LIST",
	"MAINTENANCE-TEST_RUN",
	"MAINTENANCE-DI_DO",
	"MAINTENANCE-AIR_COND_STATE",
	"MAINTENANCE-DISPLAY_TEST",

	"SETTING-ENTRANCE",
	"SETTING-MENU",
	"SETTING-MONITOR",

	"CORRECTION-MENU",
	"CORRECTION-TIME",

	"CAR_STATE-SWITCHES",
	"CAR_STATE-POWER",
	"CAR_STATE-BRAKE",
	"CAR_STATE-THREE_PHASE_AC",
	"CAR_STATE-POWER_BRAKE",

	"CONDUCTOR-INFO",
	"CONDUCTOR-SERVICE",
	"CONDUCTOR-AIR_COND",
	"CONDUCTOR-LOCATION_CORRECTION",
	"CONDUCTOR-CAR_STATE",
	"CONDUCTOR-315",

	"WORK_SETTING-TOP",
	"WORK_SETTING-TYPE",
	"WORK_SETTING-SEAT",

	"DRIVER-INFO",
	"DRIVER-REDUCE_SPEED",
	"DRIVER-ROOM_LIGHT",
	"DRIVER-LOCATION_CORRECTION",
]);
