const createPages = <const T extends readonly string[]>(arr: T) =>
	Object.fromEntries(arr.map((item) => [item, item])) as {
		[K in T[number]]: K;
	};

export const PAGE_TYPES = createPages([
	"MENU",
	"OCCUPANCY_RATE",
	"CAR_DETECTION",
	"SET_LOCATION",
	"TABLE_OF_CONTENTS",

	"OTHER_SERIES_DRIVER_INFO",
	"OTHER_SERIES_SUB_SETTING",
	"OTHER_SERIES_ANNOUNCE_1",
	"OTHER_SERIES_ANNOUNCE_2",
	"OTHER_SERIES_BROKEN",
	"OTHER_SERIES_WORK_SETTING",
	"OTHER_SERIES_WORK_SETTING_MENU",
	"OTHER_SERIES_REDUCE_SPEED",

	"MAINTENANCE_MENU",
	"MAINTENANCE_CTRL_TEST",
	"MAINTENANCE_COMM_STATE",
	"MAINTENANCE_SPEC_RECORD",
	"MAINTENANCE_BROKEN_LIST",
	"MAINTENANCE_TEST_RUN",
	"MAINTENANCE_DI_DO",
	"MAINTENANCE_AIR_COND_STATE",
	"MAINTENANCE_DISPLAY_TEST",

	"SETTING_ENTRANCE",
	"SETTING_MENU",
	"SETTING_MONITOR",

	"CORRECTION_MENU",
	"CORRECTION_TIME",

	"POWER_BRAKE",
	"THREE_PHASE_AC",
	"BRAKE",
	"POWER",
	"SWITCHES",

	"CONDUCTOR_INFO",
	"CONDUCTOR_SERVICE",
	"CONDUCTOR_AIR_COND",
	"CONDUCTOR_LOCATION_CORRECTION",
	"CONDUCTOR_315",

	"WORK_SETTING_TOP",
	"WORK_SETTING_TYPE",
	"WORK_SETTING_SEAT",

	"ROOM_LIGHT",
	"REDUCE_SPEED",
	"LOCATION_CORRECTION",
	"DRIVER_INFO",
]);

export type PageType = (typeof PAGE_TYPES)[keyof typeof PAGE_TYPES];

const PAGE_TYPE_SET = new Set<string>(Object.values(PAGE_TYPES));
export function isValidPageType(value: string): value is PageType {
	return PAGE_TYPE_SET.has(value);
}
