const createMap = <const T extends readonly string[]>(arr: T) =>
	Object.fromEntries(arr.map((item) => [item, item])) as {
		[K in T[number]]: K;
	};

export const PAGE_TYPES = createMap([
	"MENU",
	"OCCUPANCY_RATE",
	"CAR_DETECTION",
	"SET_LOCATION",
	"TABLE_OF_CONTENTS",

	"OTHER_SERIES_DRIVER_INFO",
	"OTHER_SERIES_SUB_SETTING",
	"OTHER_SERIES_ANNOUNCE_1",
	"OTHER_SERIES_ANNOUNCE_2",
	"OTHER_SERIES_BROKEN",
	"OTHER_SERIES_WORK_SETTING",
	"OTHER_SERIES_WORK_SETTING_MENU",
	"OTHER_SERIES_REDUCE_SPEED",

	"MAINTENANCE_MENU",
	"MAINTENANCE_CTRL_TEST",
	"MAINTENANCE_COMM_STATE",
	"MAINTENANCE_SPEC_RECORD",
	"MAINTENANCE_BROKEN_LIST",
	"MAINTENANCE_TEST_RUN",
	"MAINTENANCE_DI_DO",
	"MAINTENANCE_AIR_COND_STATE",
	"MAINTENANCE_DISPLAY_TEST",

	"SETTING_ENTRANCE",
	"SETTING_MENU",
	"SETTING_MONITOR",

	"CORRECTION_MENU",
	"CORRECTION_TIME",

	"POWER_BRAKE",
	"THREE_PHASE_AC",
	"BRAKE",
	"POWER",
	"SWITCHES",

	"CONDUCTOR_INFO",
	"CONDUCTOR_SERVICE",
	"CONDUCTOR_AIR_COND",
	"CONDUCTOR_LOCATION_CORRECTION",
	"CONDUCTOR_315",

	"WORK_SETTING_TOP",
	"WORK_SETTING_TYPE",
	"WORK_SETTING_SEAT",

	"ROOM_LIGHT",
	"REDUCE_SPEED",
	"LOCATION_CORRECTION",
	"DRIVER_INFO",
]);

export type PageType = (typeof PAGE_TYPES)[keyof typeof PAGE_TYPES];

export const PAGE_MODES = createMap([
	"BROKEN",
	"CAR_STATE",
	"CONDUCTOR",
	"CORRECTION",
	"DRIVER",
	"EMBEDDED_MANUAL",
	"MAINTENANCE",
	"MENU",
	"OCCUPANCY_RATE",
	"OTHER_SERIES",
	"TABLE_OF_CONTENTS",
	"WORK_SETTING",
]);
export type PageMode = (typeof PAGE_MODES)[keyof typeof PAGE_MODES];

const PAGE_TYPE_SET = new Set<string>(Object.values(PAGE_TYPES));
export function isValidPageType(value: string): value is PageType {
	return PAGE_TYPE_SET.has(value);
}

const PAGE_MODE_SET = new Set<string>(Object.values(PAGE_MODES));
export function isValidPageMode(value: string): value is PageMode {
	return PAGE_MODE_SET.has(value);
}

export const PAGE_GROUPS = createMap([
	"MENU",
	"CAR_STATE",
	"DRIVER",
	"CONDUCTOR",
	"WORK_SETTING",
	"MAINTENANCE",
	"SETTING",
	"CORRECTION",
	"OTHER_SERIES",
	"OCCUPANCY_RATE",
	"TABLE_OF_CONTENTS",
	"REDUCE_SPEED",
]);

export type PageGroup = (typeof PAGE_GROUPS)[keyof typeof PAGE_GROUPS];

export const PAGE_TO_GROUP = {
	[PAGE_TYPES.MENU]: PAGE_GROUPS.MENU,

	[PAGE_TYPES.POWER_BRAKE]: PAGE_GROUPS.CAR_STATE,
	[PAGE_TYPES.THREE_PHASE_AC]: PAGE_GROUPS.CAR_STATE,
	[PAGE_TYPES.BRAKE]: PAGE_GROUPS.CAR_STATE,
	[PAGE_TYPES.POWER]: PAGE_GROUPS.CAR_STATE,
	[PAGE_TYPES.SWITCHES]: PAGE_GROUPS.CAR_STATE,

	[PAGE_TYPES.DRIVER_INFO]: PAGE_GROUPS.DRIVER,
	[PAGE_TYPES.LOCATION_CORRECTION]: PAGE_GROUPS.DRIVER,
	[PAGE_TYPES.ROOM_LIGHT]: PAGE_GROUPS.DRIVER,

	[PAGE_TYPES.CONDUCTOR_INFO]: PAGE_GROUPS.CONDUCTOR,
	[PAGE_TYPES.CONDUCTOR_SERVICE]: PAGE_GROUPS.CONDUCTOR,
	[PAGE_TYPES.CONDUCTOR_AIR_COND]: PAGE_GROUPS.CONDUCTOR,
	[PAGE_TYPES.CONDUCTOR_LOCATION_CORRECTION]: PAGE_GROUPS.CONDUCTOR,
	[PAGE_TYPES.CONDUCTOR_315]: PAGE_GROUPS.CONDUCTOR,

	[PAGE_TYPES.WORK_SETTING_TOP]: PAGE_GROUPS.WORK_SETTING,
	[PAGE_TYPES.WORK_SETTING_TYPE]: PAGE_GROUPS.WORK_SETTING,
	[PAGE_TYPES.WORK_SETTING_SEAT]: PAGE_GROUPS.WORK_SETTING,

	[PAGE_TYPES.MAINTENANCE_MENU]: PAGE_GROUPS.MAINTENANCE,
	[PAGE_TYPES.MAINTENANCE_CTRL_TEST]: PAGE_GROUPS.MAINTENANCE,
	[PAGE_TYPES.MAINTENANCE_COMM_STATE]: PAGE_GROUPS.MAINTENANCE,
	[PAGE_TYPES.MAINTENANCE_SPEC_RECORD]: PAGE_GROUPS.MAINTENANCE,
	[PAGE_TYPES.MAINTENANCE_BROKEN_LIST]: PAGE_GROUPS.MAINTENANCE,
	[PAGE_TYPES.MAINTENANCE_TEST_RUN]: PAGE_GROUPS.MAINTENANCE,
	[PAGE_TYPES.MAINTENANCE_DI_DO]: PAGE_GROUPS.MAINTENANCE,
	[PAGE_TYPES.MAINTENANCE_AIR_COND_STATE]: PAGE_GROUPS.MAINTENANCE,
	[PAGE_TYPES.MAINTENANCE_DISPLAY_TEST]: PAGE_GROUPS.MAINTENANCE,

	[PAGE_TYPES.SETTING_ENTRANCE]: PAGE_GROUPS.SETTING,
	[PAGE_TYPES.SETTING_MENU]: PAGE_GROUPS.SETTING,
	[PAGE_TYPES.SETTING_MONITOR]: PAGE_GROUPS.SETTING,

	[PAGE_TYPES.CORRECTION_MENU]: PAGE_GROUPS.CORRECTION,
	[PAGE_TYPES.CORRECTION_TIME]: PAGE_GROUPS.CORRECTION,

	[PAGE_TYPES.OTHER_SERIES_DRIVER_INFO]: PAGE_GROUPS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_SUB_SETTING]: PAGE_GROUPS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_ANNOUNCE_1]: PAGE_GROUPS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_ANNOUNCE_2]: PAGE_GROUPS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_BROKEN]: PAGE_GROUPS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_WORK_SETTING]: PAGE_GROUPS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_WORK_SETTING_MENU]: PAGE_GROUPS.OTHER_SERIES,
	[PAGE_TYPES.OTHER_SERIES_REDUCE_SPEED]: PAGE_GROUPS.OTHER_SERIES,

	[PAGE_TYPES.OCCUPANCY_RATE]: PAGE_GROUPS.OCCUPANCY_RATE,
	[PAGE_TYPES.CAR_DETECTION]: PAGE_GROUPS.OCCUPANCY_RATE,
	[PAGE_TYPES.SET_LOCATION]: PAGE_GROUPS.OCCUPANCY_RATE,

	[PAGE_TYPES.TABLE_OF_CONTENTS]: PAGE_GROUPS.TABLE_OF_CONTENTS,

	[PAGE_TYPES.REDUCE_SPEED]: PAGE_GROUPS.REDUCE_SPEED,
} as const satisfies Record<PageType, PageGroup>;

export function getPageGroup(pageType: PageType): PageGroup {
	return PAGE_TO_GROUP[pageType];
}
